<?php
  $alums_spotlight_itm_path = '/alumni/assets/img/alumni-home/news-and-spotlight/';
  echo carousel( '', 'alums-carousel' );
?>




<?php
// On return
// Finish this: https://servicedesk.vassar.edu/incidents/97817517-alumni-page-update
// Ask Morgan why that image wasn't scraped

?>


<?php echo carousel_item(
  $alums_spotlight_itm_path.'/2022-10-12/spotlight/vassar_feigen_20220929_kr_0074-compressed.jpg',
  'is-link',
  'Photo of Amy Pullman ’71 (left) and Monica Vachher ’77 (right), and Brenda Feigen holding an award (center) and smiling with the others.'
); ?>
  <h3 class="h3">Feminist Legend Brenda Feigen ’66 Receives Spirit of Vassar Award</h3>
  <p>Before accepting the award from Amy Pullman ’71 (left) and Monica Vachher ’77 (right), Feigen (center) spoke at the College and told students to embrace activism.</p>

  <p><em>Photo: Karl Rabe</em></p>

  <?php echo cta_link(
    'https://www.vassar.edu/news/feminist-legend-brenda-feigen-66-accepts-spirit-vassar-award-tells-students-embrace-activism',
    'Read more',
    'stretched-link'
  ); ?>

<?php echo end_carousel_item(); ?>



<?php echo carousel_item(
  $alums_spotlight_itm_path.'/2022-09-16/spotlight/ifill_alum_spotlight_220915.jpg',
  'is-link',
  'Three people smile at the camera while standing in the Vassar chapel: a large, well-lit, stone-walled space'
); ?>
  <h3 class="h3">Meeting the Urgency of the Moment</h3>
  <p>Honored by the American Bar Association, Sherrilyn Ifill ’84 implored legal colleagues to help save American democracy.</p>

  <p><em>Photo: Courtesy of the American Bar Association</em></p>

  <?php echo cta_link(
    'https://www.vassar.edu/news/meeting-urgency-moment',
    'Read more',
    'stretched-link'
  ); ?>

<?php echo end_carousel_item(); ?>





<?php echo carousel_item(
  $alums_spotlight_itm_path.'/2022-09-08/spotlight/Raina-0111-22-08-kr-convocation-vassar-0188.jpg',
  'is-link',
  'Three people smile at the camera while standing in the Vassar chapel: a large, well-lit, stone-walled space'
); ?>
  <h3 class="h3">Convocation 2022</h3>
  <p>Arushi Raina ’14 (center), pictured with AAVC President Monica Vachher ’77 (left) and Stephanie Goldberg ’14, was presented with the Young Alumnae/i Achievement Award.</p>

  <p><em>Photo: Karl Rabe</em></p>

  <?php echo cta_link(
    'https://www.vassar.edu/news/convocation-2022',
    'Read more',
    'stretched-link'
  ); ?>

<?php echo end_carousel_item(); ?>




<?php echo carousel_item(
  $alums_spotlight_itm_path.'/2022-09-08/spotlight/Maccabiah-Games-22-002-horizontal-crop.jpg',
  'is-link',
  'A young man stands with his parents in the middle of a volleyball court, smiling at the camera'
); ?>
  <h3 class="h3">Brewers Past and Present Represent USA at Maccabiah Games in Israel</h3>
  <p>Former Brewers volleyball player Jake Kaplan ’22 (center), pictured with his parents, was one of three Vassar-affiliated athletes to compete.</p>

  <p><em>Photo: Courtesy of the subject</em></p>

  <?php echo cta_link(
    'https://www.vassar.edu/news/brewers-past-and-present-represent-usa-maccabiah-games-israel',
    'Read more',
    'stretched-link'
  ); ?>

<?php echo end_carousel_item(); ?>



  <?php /* echo carousel_item(
    $alums_spotlight_itm_path.'/2022-07-18/roe-v-wade-protest-16x12.jpg',
    'is-link',
    'Pro choice protestors holding up signs outside of the Supreme Court'
  ); ?>
    <h3 class="h3">The Overturning of <em>Roe v. Wade</em></h3>
    <p>Vassar professors hosted a webinar to discuss the recent U.S. Supreme Court decision, putting the loss of abortion rights in historical context and looking to the future. <em>Photo: Ian Hutchinson</em></p>

    <?php echo cta_link(
      'https://www.vassar.edu/news/overturning-roe-v-wade',
      'Read more',
      'stretched-link'
    ); ?>
  <?php echo end_carousel_item(); */ ?>



  <?php echo carousel_item(
      '/alumni/assets/img/alumni-home/sherika_sanjay_by_caleb_stein.jpg',
      'is-link',
      'Black and white photograph of two people in an embrace up to their necks in a river'
    ); ?>
      <h3 class="h3">Alum’s Photography Featured in the New York Times</h3>
      <p>Photographer Caleb Stein ’17 and Amitava Kumar, Professor of English on the Helen D. Lockwood Chair, collaborated on “An Ode to the Queen City of the Hudson,” an opinion piece in the <em>New York Times</em>. Photo by Caleb Stein ’17</p>

      <?php echo cta_link(
        'https://www.nytimes.com/2022/07/03/opinion/poughkeepsie-watering-holes-hudson-valley.html?fbclid=IwAR1ZNtwsdT1FOnR2yBvUdF_2g3M2Dc29qHMAuU08Hgt2P1Jmm9SvzH3M75U',
        'Read more',
        'stretched-link'
      ); ?>

    <?php echo end_carousel_item(); ?>



    <?php echo carousel_item(
      'https://www.vassar.edu/sites/default/files/2022-06/alum_spotlight_reunion2022.jpg',
      'is-link',
      'Marching musicians in the Class of 1972 parade on Vassar Campus'
    ); ?>
    <h3 class="h3">Reunion 2022 Highlights!</h3>
  <p>This year’s joyous, in-person gathering drew more than 1,500 alums, friends, and family members representing classes that spanned 60 years. Catch up on the festivities! <em>Photo: Karl Rabe</em></p>

  <?php echo cta_link(
    'https://www.vassar.edu/news/reunion-2022-highlights',
    'Read more',
    'stretched-link'
  ); ?>

    <?php echo end_carousel_item(); ?>




    <?php /* echo carousel_item(
      'https://www.vassar.edu/sites/default/files/2022-06/alum_spotlight_marina_bayeva.jpg',
      'is-link',
      'Marina Bayeva hugging a dog on a rocky outcrop on a mountainside'
    ); ?>
          <h3 class="h3">Marina Bayeva ’06: Helping Ukraine’s Displaced Animals</h3>
       <p>Since the invasion of Ukraine began, Marina Bayeva ’06 has been collecting money for shelters in her native country and coordinating rescue efforts for animals there. <em>Photo: Courtesy of the subject.</em></p>

       <?php echo cta_link(
         'https://www.vassar.edu/news/marina-bayeva-06',
         'Read more',
         'stretched-link'
       ); ?>

    <?php echo end_carousel_item(); */ ?>



<?php echo end_carousel(); ?>
