<?php






function admissionExploreCampusCarousel () {
    return <<<TMP
<div class="featureImage-text-ticker media-carousel fade-nonselected full" id="gallery">

  <div class="carousel-cell">
    <div class="carousel-cell-content">
      <div class="image-container">
        <img src="/assets/images/placeholders/main-placeholder.jpg" />
      </div>
       <div class="figcaption pt-5">
            <h3 class="h3">The Libraries</h3>
            <p>With more than 1 million volumes, the Vassar libraries hold one of the largest liberal arts collections in the country. In the Thompson Memorial Library, sit and study in the main reading room beneath the stunning Cornaro stained glass window as the sun streams through.
            </p>
      </div>
    </div>
  </div>


    <div class="carousel-cell">
    <div class="carousel-cell-content">
      <div class="image-container">
        <img src="/assets/images/placeholders/main-placeholder.jpg" />
      </div>
       <div class="figcaption pt-5">
            <h3 class="h3">The Frances Lehman Loeb Art Center</h3>
            <p>Founded in 1864 as the Vassar College Art Gallery, the center is one of the only nationally known museums on a college campus. Today it is home to 21,000 works including by Rembrandt, Pablo Picasso, Georgia O’Keeffe, and Francis Bacon.
</p>
      </div>
    </div>
  </div>

    <div class="carousel-cell">
    <div class="carousel-cell-content">
      <div class="image-container">
        <img src="/assets/images/placeholders/main-placeholder.jpg" />
      </div>
       <div class="figcaption pt-5">
            <h3 class="h3">The Bridge for Laboratory Sciences</h3>
            <p>Designed as a bridge across the Fonteyn Kill wetland, our environmentally friendly, dynamic STEM facility comprises a network of interdisciplinary laboratories that connects the integrated sciences with humanities. The state-of-the-art building was the first in the U.S. to use so much of a special, innovative type of bird-friendly glass, with a coating visible to birds but almost invisible to humans.
</p>
      </div>
    </div>
  </div>


    <div class="carousel-cell">
    <div class="carousel-cell-content">
      <div class="image-container">
        <img src="/assets/images/placeholders/main-placeholder.jpg" />
      </div>
       <div class="figcaption pt-5">
            <h3 class="h3">The Shakespeare Garden</h3>
            <p>The second oldest garden in the United States, this tranquil space is appreciated by the Vassar community and visitors alike.
</p>
      </div>
    </div>
  </div>



      <div class="carousel-cell">
    <div class="carousel-cell-content">
      <div class="image-container">
        <img src="/assets/images/placeholders/main-placeholder.jpg" />
      </div>
       <div class="figcaption pt-5">
            <h3 class="h3">The Vassar Farm and Ecological Preserve</h3>
            <p>This 500-acre green space comprises a multitude of habitats including streams, wetlands, ponds, forest, and old fields populated by a diversity of flora and fauna. This is an invaluable resource for Vassar faculty and students conducting scientific research.
</p>
      </div>
    </div>
  </div>

TMP;
}
