<?php


function alumniReunionsCarousel () {
    return <<<TMP

<div class="featureImage-text-ticker media-carousel fade-nonselected full" id="gallery">

<div class="carousel-cell">
    <div class="carousel-cell-content">
        <div class="image-container">
        <img src="/alumni/assets/img/alumni-calendar/reunion/slideshow/Reunion_1806_CS_424.jpg" />
        </div>
    </div>
</div>


<div class="carousel-cell">
    <div class="carousel-cell-content">
        <div class="image-container">
        <img src="/alumni/assets/img/alumni-calendar/reunion/slideshow/Vassar_20190508_Social_KR_2730.jpg" />
        </div>
    </div>
</div>

<div class="carousel-cell">
    <div class="carousel-cell-content">
        <div class="image-container">
        <img src="/alumni/assets/img/alumni-calendar/reunion/slideshow/0098_13_06_BL_8847.jpg" />
        </div>
    </div>
</div>



<div class="carousel-cell">
    <div class="carousel-cell-content">
        <div class="image-container">
        <img src="/alumni/assets/img/alumni-calendar/reunion/slideshow/0054_15_06_CS_099.jpg" />
        </div>
    </div>
</div>










  </div>

TMP;
}
