<?php


function admissionExploreHudsonCarousel () {
    return <<<TMP

<div class="featureImage-text-ticker media-carousel fade-nonselected full" id="gallery">

<div class="carousel-cell">
    <div class="carousel-cell-content">
        <div class="image-container">
        <img src="/admission/assets/images/explore/hudson/0073-21-06-kr-summer-vassar-0064.jpg" alt="An ornate metal clock stands in the middle of a traffic island, with small stores on both sides." />
        </div>
        <div class="figcaption pt-5">
            <h3 class="h3">Arlington</h3>
            <p>The Arlington District of Poughkeepsie is a vibrant community in Dutchess County. It’s home to Vassar and features a rich selection of cuisine, specialty retail shops, and community events.
        </p>
        </div>
    </div>
</div>


<div class="carousel-cell">
    <div class="carousel-cell-content">
        <div class="image-container">
        <img src="/admission/assets/images/explore/hudson/0195-16-10-kr-farm-market-vassar-0017.jpg" alt="A person places fruit on a large table, under a large, outdoor tent." />
        </div>
        <div class="figcaption pt-5">
            <h3 class="h3">Arlington Farmers’ Market</h3>
            <p>Vassar hosts Arlington Farmers’ Market seasonally on the Alumnae House great lawn from June through October. The market features dozens of vendors selling local goods.
        </p>
        </div>
    </div>
</div>

<div class="carousel-cell">
    <div class="carousel-cell-content">
        <div class="image-container">
        <img src="/admission/assets/images/explore/hudson/PM_20190530_Bocuse_311.jpg" alt="A person wearing white cooking clothes carefully assembles a fancy salad." />
        </div>
        <div class="figcaption pt-5">
            <h3 class="h3">The Culinary Institute of America</h3>
            <p>Dine at a variety of student-staffed restaurants including the American Bounty Restaurant, The Bocuse Restaurant, Ristorante Caterina de’ Medici, and the Apple Pie Bakery Café.
        </p>
        </div>
    </div>
</div>



<div class="carousel-cell">
    <div class="carousel-cell-content">
        <div class="image-container">
        <img src="/admission/assets/images/explore/hudson/Dia_Beacon_10_RBa1.jpg" alt="A series of giant, circular metal sculptures sit in a large art gallery." />
        </div>
        <div class="figcaption pt-5">
            <h3 class="h3">Dia: Beacon Art Museum</h3>
            <p>One of the largest exhibition spaces in the country for modern and contemporary art.
        </p>
        </div>
    </div>
</div>


<div class="carousel-cell">
    <div class="carousel-cell-content">
        <div class="image-container">
        <img src="/admission/assets/images/explore/hudson/Depositphotos_53747507_XL.jpg" alt="Two metal figures, sculptures of Franklin and Eleanor Roosevelt, sit in a large, outdoor space." />
        </div>
        <div class="figcaption pt-5">
            <h3 class="h3">Franklin D. Roosevelt Residence & The Presidential Library Museum</h3>
            <p>The place where the 32nd U.S. president called home. Home to FDR’s official papers, books, and other memorabilia, as well as the papers of First Lady Eleanor Roosevelt.</p>
        </div>
    </div>
</div>

<div class="carousel-cell">
    <div class="carousel-cell-content">
        <div class="image-container">
        <img src="/admission/assets/images/explore/hudson/0072-21-06-kr-mohonk-vassar-0066.jpg" alt="A view from a mountaintop out over a vast open space, with blue sky and forest-covered mountains below and in the distance." />
        </div>
        <div class="figcaption pt-5">
            <h3 class="h3">The Gunks</h3>
            <p>Short for Shawangunks, this world-class hiking and climbing spot offers spectacular views and some of the best climbing in the eastern United States.
        </p>
        </div>
    </div>
</div>



<div class="carousel-cell">
    <div class="carousel-cell-content">
        <div class="image-container">
        <img src="/admission/assets/images/explore/hudson/Storm_King_07_TT_166-crop.jpg" alt="A large, abstract sculpture made of curved metal sits in the middle of a natural area during the fall, with orange trees behind it." />
        </div>
        <div class="figcaption pt-5">
            <h3 class="h3">Storm King Art Center</h3>
            <p>This open-air museum located in New Windsor contains a vast collection of contemporary outdoor sculptures.
</p>
        </div>
    </div>
</div>

<div class="carousel-cell">
    <div class="carousel-cell-content">
        <div class="image-container">
        <img src="/admission/assets/images/explore/hudson/0148-18-11-kr-walkway-vassar-5527.jpg" alt="Two students facing away from the viewer wheel their bikes along a long concrete pathway on a bridge overlooking the Hudson river." />
        </div>
        <div class="figcaption pt-5">
            <h3 class="h3">Walkway Over the Hudson</h3>
            <p>At 1.28 miles long, this is the longest elevated pedestrian bridge in the world.</p>
        </div>
    </div>
</div>

  </div>

TMP;
}
