<?php


function inTheMediaCarousel() {
    return <<<TMP
 
<div class="featureImage-text-ticker media-carousel fade-nonselected full" id="gallery">

  <div class="carousel-cell">
    <div class="carousel-cell-content">
      <div class="image-container">
        <img src="/mockups-unused/advancement-home/assets/images/in-the-media/blum.jpg" />
      </div>
       <div class="figcaption pt-5">
        <small class="mb-3 d-block">June 21, 2022</small>
<p><strong>Jason Blum ’91’s</strong> $10 million gift to <strong>Vassar College</strong> was the subject of a <a href="https://variety.com/2022/film/news/jason-blum-blumhouse-vassar-college-scholarship-1235299680/"><em>Variety</em></a> story.</p>
          <a href="https://variety.com/2022/film/news/jason-blum-blumhouse-vassar-college-scholarship-1235299680/" class="px-0 btn btn-link arrow">Read more on <em>Variety</em>.</a>
      </div>
    </div>
  </div>

    <div class="carousel-cell">
    <div class="carousel-cell-content">
      <div class="image-container">
        <img src="/mockups-unused/advancement-home/assets/images/in-the-media/ifill.jpg" />
         </div>
      <div class="figcaption pt-5">
        <small class="mb-3 d-block">June 21, 2022</small>
        <p>The Ford Foundation has awarded a senior fellowship to <strong>Sherrilyn Ifill ’84</strong>, President and Director-Counsel Emeritus of the NAACP Legal Defense Fund, “to continue her work on strengthening American democracy,” as announced by the <a href="https://www.fordfoundation.org/news-and-stories/news-and-press/news/sherrilyn-ifill-joins-ford-foundation-as-a-senior-fellow/">foundation</a>.</p>
        <a href="https://www.fordfoundation.org/news-and-stories/news-and-press/news/sherrilyn-ifill-joins-ford-foundation-as-a-senior-fellow/" class="px-0 btn btn-link arrow">Read more at the Ford Foundation</a>

      </div>
    </div>
  </div>

      <div class="carousel-cell">
    <div class="carousel-cell-content">
      <div class="image-container">
             <img src="/mockups-unused/advancement-home/assets/images/in-the-media/goldberg.jpg" />
          </div>
 <div class="figcaption pt-5">
<small class="mb-3 d-block">July 1, 2022</small>
<p>Victims’ rights attorney <strong>Carrie Goldberg ’99</strong> (pictured) was quoted in an <em>Insider</em> story about the misogyny stemming from the recent Amber Heard/Johnny Depp trial.</p>

        <a href="https://www.insider.com/internet-trolls-using-amber-heard-name-dog-whistle-lawyer-2022-7" class="px-0 btn btn-link arrow">Read more on <em>Insider</em></a>

      </div>
    </div>
  </div>

  </div>

TMP;
}