<style>

.carousel-cell .figcaption p {
    line-height: 1.3;
}
.carousel-cell .figcaption h3 {
  line-height: 1.1;
}
</style>

<?php
  $alums_spotlight_itm_path = '/alums/assets/img/alums-home/news-and-spotlight/';
  echo carousel( '', 'alums-carousel' );
?>





<?php echo carousel_item(
  $alums_spotlight_itm_path.'/2024-06-27/spotlight/0094-24-06-kma-groundbreaking-vassar-6491.jpg',
  'is-link',
  'Five people wearing construction helmets stand over a mound of dirt, holding shovels that are pushed into the dirt. They are smiling at the camera.'
); ?>
  <h3 class="h3">Vassar’s “Game-Changing” Admission and Career Center Takes a Big Step Forward</h3>
  <p>World-class. Transformational. Game-changing. Those were just a few of the adjectives used to describe The Dede Thompson Bartlett Center for Admission and Career Education at a June 12th groundbreaking ceremony.</p>
  <p><em>Center: Dede Thompson Bartlett ’65<br>Photo: Kelly Marsh</em></p>

  <?php echo cta_link(
    'https://www.vassar.edu/news/vassars-game-changing-admission-and-career-center-takes-a-big-step-forward',
    'Read more',
    'stretched-link'
  ); ?>

<?php echo end_carousel_item(); ?>






<?php echo carousel_item(
  $alums_spotlight_itm_path.'/2024-06-27/spotlight/Laura-Alice-Marian.jpg',
  'is-link',
  'A person with brown hair and a long floral-patterned dress stands outside, speaking in front of a wooden podium with the word Vassar on it.'
); ?>
  <h3 class="h3">Embracing Every Chapter</h3>
  <p>When Alice Belgray ʼ59, née Bunzl, came to Vassar, she was planning to study math, but found herself gravitating toward the rich musical education at the College. At 86, Alice still has a passion for music and also children’s literature.</p>
  <p><em>Photo: Courtesy of Alice Belgray ʼ59</em></p>

  <?php echo cta_link(
    'https://www.vassar.edu/news/embracing-every-chapter-alice-belgray',
    'Read more',
    'stretched-link'
  ); ?>

<?php echo end_carousel_item(); ?>







<?php echo carousel_item(
  $alums_spotlight_itm_path.'/2024-06-17/spotlight/reunion.jpg',
  'is-link',
  'A black-and-white historical photo of a person with long hair, holding a camera and looking up.'
); ?>
  <h3 class="h3">Reunion 2024</h3>
  <p>Nearly 1,300 alums returned to campus for a full weekend of fun!</p>
  <p><em>Photo: Stockton Photo, Inc.</em></p>

  <?php echo cta_link(
    'https://www.vassar.edu/news/reunion-2024-highlights',
    'Read more',
    'stretched-link'
  ); ?>

<?php echo end_carousel_item(); ?>




<?php echo carousel_item(
  $alums_spotlight_itm_path.'/2024-05-02/spotlight/alums-20240502-triennial.jpg',
  'is-link',
  'Two people stand together while a third takes a photo with a phone. One person has a badge with the Vassar logo; the badge says "Nancy" on it.'
); ?>
  <h3 class="h3">AAAVC’s Triennial 2024: Reconnecting and Remembering</h3>
  <p><em>Photo: Kelly Marsh</em></p>

  <?php echo cta_link(
    'https://www.vassar.edu/news/aaavcs-triennial-2024-reconnecting-and-remembering',
    'Read more',
    'stretched-link'
  ); ?>

<?php echo end_carousel_item(); ?>  


<?php echo carousel_item(
  $alums_spotlight_itm_path.'/2024-05-02/spotlight/20240502-alumnae-house.jpg',
  'is-link',
  'A group of people walk in front of several Vassar buildings. One is holding a banner that says "100 Years of Alumnae House".'
); ?>
  <h3 class="h3">Vassar Celebrates Alumnae House’s 100th Birthday in Style</h3>
  <p><em>Photo: Karl Rabe</em></p>

  <?php echo cta_link(
    'https://www.vassar.edu/news/vassar-celebrates-alumnae-houses-100th-birthday',
    'Read more',
    'stretched-link'
  ); ?>

<?php echo end_carousel_item(); ?>  


<?php echo carousel_item(
  $alums_spotlight_itm_path.'/2024-05-02/spotlight/jess-chong-20240502.jpg',
  'is-link',
  'Two people stand outside, maneuvering some very large wooden puzzle pieces.'
); ?>
  <h3 class="h3">Getting Real</h3>
  <p>Jessica Chong ’08 becomes second alum to compete on <em>Survivor</em>.</p>
  <p><em>Photo: Courtesy of CBS/Paramount</em></p>

  <?php echo cta_link(
    'https://www.vassar.edu/news/getting-real',
    'Read more',
    'stretched-link'
  ); ?>

<?php echo end_carousel_item(); ?>  






<?php echo carousel_item(
  $alums_spotlight_itm_path.'/2024-03-28/spotlight/admin_fellows_zickl_4x3_resized.jpg',
  'is-link',
  'A person with long brown hair and a maroon athletic sweater stands outside in front of an athletic net, holding a ball in one hand and a helmet in the other.'
); ?>
  <h3 class="h3">Administrative Fellowship Program Develops Leadership Capacity for Higher Ed and Other Key Fields</h3>
  <p>Claire Zickl ’23 (pictured) is a President’s Administrative Fellow for Student Athlete Welfare and Compliance.</p>
  <p><em>Photo: Grace Adams Ward ’24</em></p>

  <?php echo cta_link(
    'https://www.vassar.edu/news/administrative-fellowships-a-unique-opportunity-for-recent-vassar-grads',
    'Read more',
    'stretched-link'
  ); ?>

<?php echo end_carousel_item(); ?>  








<?php echo carousel_item(
  $alums_spotlight_itm_path.'/2024-03-28/spotlight/simmons_4x3_resized.jpg',
  'is-link',
  'A person with long brown hair and a black-and-white-patterned shirt sits in a room at a table surrounded by other people, speaking.'
); ?>
  <h3 class="h3">A Winding Path Will Get You There</h3>
  <p>Rachel Simmons ’96, author and founder of the nonprofit Girls Leadership, offered career advice to students during campus visit.</p>
  <p><em>Photo: Kelly Marsh</em></p>

  <?php echo cta_link(
    'https://www.vassar.edu/news/alum-students-winding-path-will-get-you-there',
    'Read more',
    'stretched-link'
  ); ?>

<?php echo end_carousel_item(); ?>









<?php echo carousel_item(
  $alums_spotlight_itm_path.'/2024-02-22/spotlight/jan_farrington_4x3.jpg',
  'is-link',
  'A person with mid-length gray hair and a blue patterned shirt smiles at the viewer. The person is outside, with trees and a tree trunk visible in the background.'
); ?>
  <h3 class="h3">Embracing Every Chapter: The Happy Camper, Jan Farrington ’46</h3>
  <p>A new series on older alums begins.</p>
  <p><em>Photo: Samuel Stuart Photography</em></p>

  <?php echo cta_link(
    'https://www.vassar.edu/news/embracing-every-chapter-happy-camper-jan-farrington-46',
    'Read more',
    'stretched-link'
  ); ?>

<?php echo end_carousel_item(); ?>



<?php echo carousel_item(
  $alums_spotlight_itm_path.'/2024-02-22/spotlight/schwarzman_scholarships_4x3.jpg',
  'is-link',
  'A wood-paneled conference room with people in it. In the foreground, several people sit at a table covered with paper, discussing something.'
); ?>
  <h3 class="h3">Two Vassar Grads Embark on Study in China After Winning Prestigious Schwarzman Scholarships</h3>
  <p>The awardees are Frank Najarro-Izquierdo ’18 (pictured) and Aena Khan ’22.</p>
  <p><em>Photo: Karl Rabe</em></p>

  <?php echo cta_link(
    'https://www.vassar.edu/news/two-vassar-grads-embark-on-study-in-china-after-winning-prestigious-schwarzman-scholarships',
    'Read more',
    'stretched-link'
  ); ?>

<?php echo end_carousel_item(); ?>


<?php echo end_carousel(); ?>
